### ISSUE TITLE
Warning: unserialize(): Extra data starting at offset 198429 of 210053 bytes in ProcessSessionInfo/Session.php:30

### ISSUE THREAD

**Issue by adrianbj** [Toutouwai/ProcessSessionInfo#3]
If you add a `bd($session_data, $offset);` before that line you'll see that some of the session data includes html from admin. Looks like mostly for the nav submenu items etc.

There are a few google results pointing to a change in the way PHP8.3 no longer ignores offset errors.

Let  me know if you have any problems reproducing and/or need more details.

**Comment by Toutouwai** [comment]
Hi @adrianbj,

I can see HTML there but it doesn't look like it would be invalid. It's in the "AdminThemeUikit" item and it decodes for me without any errors or notices in PHP 8.3.

Is it something you're seeing in all the session data on all sites or is it just a single session that's got corrupted somehow? If something (ProcessWire?) is writing data to session in a way that's invalid then wouldn't the fix need to go there rather than at the point of reading?

As I can't reproduce it here are you able to check if the warning can be avoided with try/catch? Or have you seen a recommendation on how to handle an attempt to unserialize data that might be invalid?

**Comment by Toutouwai** [comment]
I saw this article: https://wiki.php.net/rfc/unserialize_warn_on_trailing_data

It says:

>As serialize returns a valid serialization payload without trailing bytes, having trailing bytes within the input to unserialize implies that the serialization payload was _erroneously modified after-the-fact_. Silently accepting such serialization payload therefore is likely to mask (serious) issues within the application’s handling of (serialized) data and is therefore undesirable.

So that makes me think that the warning is the correct outcome and it means there's an error that needs fixing somewhere else.

**Comment by Toutouwai** [comment]
The code that the module uses to read from the session data is from this comment: https://www.php.net/manual/en/function.session-decode.php#108037

It says:

> It doesn't use a regular expression but rather the reversibility of the serialize operation and the 'feature' that serialize ignores all further input when it thinks it's done.

So it must be expected that session data can contain data that `unserialize()` can't handle, and now that PHP is starting to give warnings it might be that this approach is no longer viable.

If there's nothing sensitive in it are you able to share the raw session data with me so I can experiment a bit? So basically a `bdb()` dump of `$session_data` at the top of the `unserialize_php()` method.

Thanks.

**Comment by Toutouwai** [comment]
@adrianbj, don't worry about sending me your session data - my test site is starting to throw some warnings now. I'll see if I can find a solution.

**Comment by adrianbj** [comment]
Thanks @Toutouwai - glad you're seeing it at your end now also, but do let me know if there is anything I can do to help.

Not sure if either of these help
https://stackoverflow.com/questions/10152904/how-to-repair-a-serialized-string-which-has-been-corrupted-by-an-incorrect-byte

https://gist.github.com/phred/1201412

That gist as it is doesn't solve the problem, but I wonder if it would be a cleaner replacement for your current approach anyway? Maybe it doesn't do exactly the same thing?

**Comment by Toutouwai** [comment]
@adrianbj, v0.1.1 avoids the error notices by temporarily turning off error reporting and then turning it on again after the raw session data is read.

As I understand it, the class I'm using to read the raw session data is deliberately feeding unserialize() data that isn't quite valid and letting unserialize() sort it out. So although PHP 8.3 wants to warn users about the error, in this case the "error" is deliberate and expected, so the notice isn't useful. I believe this is the only practical way to work out where the boundaries are within the raw session string, as all the comments I've seen say that other approaches using things like regex are bound to fail. The gist you linked to is using the same approach and gives the same errors in PHP 8.3, and it doesn't allow for when the serialize_handler is php_binary so I think it's better to stick with the class I'm already using.

Let me know if this update doesn't solve it for you or if you have any other thoughts.

**Comment by adrianbj** [comment]
Hey @Toutouwai - that sounds like a perfectly reasonable solution given what's happening.

I am curious why you didn't just go with the shutup operator
`$info = @\Session::unserialize($contents);` 
but it doesn't really matter either way obviously.

Thanks.

**Comment by Toutouwai** [comment]
Thanks @adrianbj, I previously tried the `@` operator specifically on `unserialize()` and was still seeing error notices, but I was trying other code changes at the same time and it must have caused a higher level of error that can't be suppressed by `@` in PHP 8.

Now that I try it again `@` is working so in v0.1.2 I've switched to that just for the two `unserialize()` calls as the suppression will be more targeted that way. Thanks for the suggestion.
